# Generated by Django 6.1 on 2026-08-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_event_delete_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='incident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='incident_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.CharField(default='LOW', max_length=20),
        ),
    ]
