# Generated by Django 6.1 on 2026-08-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_event_incident_event_incident_reason_event_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='response_action',
            field=models.TextField(blank=True),
        ),
    ]
