# Generated by Django 6.1 on 2026-08-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_event_response_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
