# Generated by Django 6.1 on 2026-08-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_event_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='incident_status',
            field=models.CharField(default='DETECTED', max_length=30),
        ),
    ]
