# Generated by Django 6.1 on 2026-08-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_event_incident_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='escalation_level',
            field=models.CharField(default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='incident_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='response_action',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='service_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='solution',
            field=models.TextField(blank=True, default=''),
        ),
    ]
