# Generated by Django 6.1 on 2026-08-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_event_escalation_level_event_resolved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('root_cause', models.CharField(blank=True, default='', max_length=100)),
                ('root_cause_confidence', models.IntegerField(default=0)),
                ('root_cause_reason', models.TextField(blank=True, default='')),
                ('priority', models.CharField(default='LOW', max_length=20)),
                ('correlation_score', models.IntegerField(default=0)),
                ('highest_severity', models.CharField(default='INFO', max_length=20)),
                ('escalation_required', models.BooleanField(default=False)),
                ('escalation_score', models.IntegerField(default=0)),
                ('escalation_level', models.CharField(default='NONE', max_length=30)),
                ('remediation_action', models.CharField(blank=True, default='', max_length=100)),
                ('remediation_status', models.CharField(default='NOT_EXECUTED', max_length=30)),
                ('verification_status', models.CharField(default='PENDING', max_length=50)),
                ('final_status', models.CharField(default='OPEN', max_length=50)),
                ('before_anomaly_score', models.IntegerField(default=0)),
                ('after_anomaly_score', models.IntegerField(default=0)),
                ('before_failure_rate', models.FloatField(default=0)),
                ('after_failure_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
